// Generated by CoffeeScript 1.6.3
/* Copyright (c) 2014 MIT Media Lab, https://qnt.io*/


(function() {
  var getQueryString, quantifyObject;

  getQueryString = function(obj) {
    var k, s, v;
    s = [];
    for (k in obj) {
      v = obj[k];
      s.push(encodeURIComponent(k) + "=" + encodeURIComponent(v));
    }
    return s.join("&");
  };

  quantifyObject = {
    _version: "0.0.1",
    _key: "key",
    _project: "earth_tapestry",
    _allowedEntities: ['displayMetrics'],
    init: function(projectName, key) {
      this._project = projectName;
      this._key = key;
    },
    getKey: function() {
      return this._key;
    },
    getVersion: function() {
      return this._version;
    },
    getProjectName: function() {
      return this._project;
    },
    getContestents: function() {},
    getAccount: function() {},
    setAccount: function() {},
    vote: function() {},
    getSearchResults: function() {},
    getResults: function() {},
    getMetrics: function(limit, mode, callback) {
      var data;
      data = {
        limit: limit,
        mode: mode
      };
      return this._quantifyHTTP("get", "displaymetrics", data, callback);
    },
    _quantifyHTTP: function(method, entity, data, callback) {
      var base, qntData, url, xhr;
      base = "http://quantify.media.mit.edu:8888/api";
      qntData = {
        pID: this._project,
        key: this._key
      };
      url = base + "/" + entity + "?" + getQueryString(data) + "&" + getQueryString(qntData);
      console.log("Full Request URL:", url);
      xhr = new XMLHttpRequest();
      xhr.overrideMimeType("application/json");
      xhr.onload = function(resp) {
        return callback(JSON.parse(resp.target.responseText));
      };
      xhr.open(method, url, true);
      return xhr.send();
    }
  };

  window.qnt = quantifyObject;

  console.log("Ran");

}).call(this);
