// Generated by CoffeeScript 1.8.0

/* Copyright (c) 2014 MIT Media Lab, https://qnt.io */

(function() {
  var getAccountName, getQueryString, quantifyObject,
    __slice = [].slice;

  getQueryString = function(obj) {
    var k, s, v;
    s = [];
    for (k in obj) {
      v = obj[k];
      if (v) {
        s.push(encodeURIComponent(k) + "=" + encodeURIComponent(v));
      }
    }
    return s.join("&");
  };

  getAccountName = function() {};

  quantifyObject = {
    _version: "0.0.1",
    _base_url: "https://www.qnt.io/api",
    _project: "",
    _key: "key",
    _user: "",
    init: function(projectName, key) {
      this._project = projectName;
      this._key = key;
      this._quantifyHTTP("get", "checkusercookie", {}, function(checkCookieResult) {
        if (checkCookieResult[0]['uID']) {
          return qnt._user = checkCookieResult[0]['uID'];
        } else {
          console.log("No cookie found. Creating new user");
          return qnt._quantifyHTTP("get", "createuser", {}, function(e) {
            return qnt._user = e['uID'];
          });
        }
      });
    },
    getKey: function() {
      return this._key;
    },
    getVersion: function() {
      return this._version;
    },
    getUser: function() {
      return this._user;
    },
    getProjectName: function() {
      return this._project;
    },
    checkUserNameCookie: function(callback) {
      return this._quantifyHTTP("get", "checkusercookie", {}, callback);
    },
    createUserName: function(callback) {
      return this._quantifyHTTP("get", "createuser", {}, callback);
    },
    setAccount: function(user) {
      if (validatedUser(user)) {
        this._user = user;
        return true;
      } else {
        return false;
      }
    },
    getContent: function(cID, callback) {
      var data;
      data = {
        cID: cID
      };
      return this._quantifyHTTP("get", "content", data, callback);
    },
    getScores: function(cID, callback) {
      var data;
      data = {
        cID: cID
      };
      return this._quantifyHTTP("get", "scores", data, callback);
    },
    getSearchResults: function() {
      var callback, data, limit, mID, metric_score, skip, _arg, _i;
      mID = arguments[0], metric_score = arguments[1], _arg = 4 <= arguments.length ? __slice.call(arguments, 2, _i = arguments.length - 1) : (_i = 2, []), callback = arguments[_i++];
      skip = _arg[0], limit = _arg[1];
      data = {
        mID: mID,
        metric_score: metric_score,
        skip: skip,
        limit: limit
      };
      return this._quantifyHTTP("get", "search", data, callback);
    },
    getMetrics: function(mID) {
      var data;
      data = {
        mID: mID
      };
      return this._quantifyHTTP("get", "metric", data, callback);
    },
    vote: function() {
      var callback, data, mID, uID, vote_data, vote_result, voter_ip, _arg, _i;
      mID = arguments[0], vote_data = arguments[1], uID = arguments[2], vote_result = arguments[3], _arg = 6 <= arguments.length ? __slice.call(arguments, 4, _i = arguments.length - 1) : (_i = 4, []), callback = arguments[_i++];
      voter_ip = _arg[0];
      data = {
        mID: mID,
        uID: uID,
        vote_data: vote_data,
        vote_result: vote_result,
        voter_ip: voter_ip
      };
      return this._quantifyHTTP("post", "vote", data, callback);
    },
    getContestants: function() {
      var callback, data, mID, mode, num_desired_contestants, _arg, _i;
      mID = arguments[0], mode = arguments[1], _arg = 4 <= arguments.length ? __slice.call(arguments, 2, _i = arguments.length - 1) : (_i = 2, []), callback = arguments[_i++];
      num_desired_contestants = _arg[0];
      data = {
        mID: mID,
        mode: mode,
        num_desired_contestants: num_desired_contestants
      };
      return this._quantifyHTTP("get", "contestants", data, callback);
    },
    getResults: function() {
      var callback, data, limit, mID, skip, sort, _arg, _i;
      mID = arguments[0], _arg = 3 <= arguments.length ? __slice.call(arguments, 1, _i = arguments.length - 1) : (_i = 1, []), callback = arguments[_i++];
      limit = _arg[0], skip = _arg[1], sort = _arg[2];
      data = {
        mID: mID,
        sort: sort,
        skip: skip,
        limit: limit
      };
      return this._quantifyHTTP("get", "results", data, callback);
    },
    getDisplayMetrics: function() {
      var callback, data, limit, mode, _arg, _i;
      mode = arguments[0], _arg = 3 <= arguments.length ? __slice.call(arguments, 1, _i = arguments.length - 1) : (_i = 1, []), callback = arguments[_i++];
      limit = _arg[0];
      data = {
        mode: mode,
        limit: limit
      };
      return this._quantifyHTTP("get", "displaymetrics", data, callback);
    },
    getProjectStats: function(callback) {
      return this._quantifyHTTP("get", "projectstats", {}, callback);
    },
    _quantifyHTTP: function(method, entity, data, callback) {
      var qntData, url, xhr;
      qntData = {
        pID: this._project,
        key: this._key
      };
      url = this._base_url + "/" + entity + "?" + getQueryString(data) + "&" + getQueryString(qntData);
      xhr = new XMLHttpRequest();
      xhr.overrideMimeType("application/json");
      xhr.withCredentials = true;
      xhr.onload = function(resp) {
        return callback(JSON.parse(resp.target.responseText));
      };
      xhr.open(method, url, true);
      return xhr.send();
    }
  };

  window.qnt = quantifyObject;

  console.log("Quantify Library Launched");

}).call(this);
